Add generated output.jsons for docs examples (#8535)
This allows us to show the results of example evaluation before the user
clicks evaluate, but also for chatbots to see the output when viewing
without interaction.

Signed-off-by: Charlie Egan <charlie_egan@apple.com>

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -60,3 +60,16 @@ markdownlint-check:
 .PHONY: spell-check
 spell-check:
 	vale --config=.vale.ini .
+
+.PHONY: gen
+gen:
+	./bin/eval-examples.sh
+
+.PHONY: gen-check
+gen-check:
+	./bin/eval-examples.sh
+	@if [ -n "$$(git status --porcelain)" ]; then \
+		echo "Error: working directory is not clean after running gen"; \
+		git diff; \
+		exit 1; \
+	fi
